### ISSUE TITLE
9일차 문제(20190129)

### ISSUE THREAD

**Issue by yelgit** [hrkim28/TCT#10]
문제)
  현우는 초등학생인 여동생의 수학 숙제를 도와주고 있었다.
  현우는 동생을 좀 더 잘 가르치고 싶어 답을 구하는 과정을 되도록 자세히 알려주려고 오른쪽에서 왼쪽으로 순차적으로 계산하는 과정을 보여주고자 한다.

  단, 일반적인 수식과 같이 곱하기(*)와 나누기(/)는 연산자 우선순위가 높으므로 먼저 계산해야 한다. 현우를 도와 수식을 입력 받으면 계산과정과 결과를 보여주는 코드를 작성하도록 하자.

입력)
  한 줄로 숫자와 사칙 연산 기호 +, -, *, /로 이루어진 수식이 입력된다.

출력)
  한 줄마다 오른쪽에서 왼쪽으로 한 단계씩 계산된 결과와 나머지 수식을 출력한다.

예시1)
- 입력
   9+5-4+8

- 출력
  14-4+8
  10+8 
  18

예시 2)
- 입력
  5+6*3-6/2+5

- 출력
  5+18-6/2+5
  5+18-3+5
  23-3+5
  20+5
  25

**Comment by yelgit** [comment]
출제자가 문제를 이해할 수 있는 문제를 고르다 보니 너무 난이도가 낮아졌네요. 이해 하시기 바랍니다.^^

**Comment by yelgit** [comment]
다음 출제자는 김진귀 선임 입니다. 수고해 주세요~~

**Comment by Kimsiwon75** [comment]
우선 출첵

**Comment by hjkimsky** [comment]
우선 출첵

**Comment by youngmi-won** [comment]
난이도 안낮은데요..ㅋㅋ

**Comment by junwc** [comment]
저도 출첵..그리고, 금일 파이썬 리뷰어는 김진귀 선임입니다.

**Comment by ximpley** [comment]
저도 출석 체크합니다. 이동근 책임님 감동했습니다. 문제 좋아요..

**Comment by choiswon** [comment]
일단 출첵하고, 고민 고민중...

**Comment by srjie** [comment]
너무 어렵네요 ㅜㅜ

**Comment by BBOMS** [comment]
저도 출첵요! 문제가 좋아서 풀고 싶은데... 파이썬 그룹이라 파이썬으로 풀어야해서요 아직 파이썬 p도 몰라서 이번주 좀 더 study하고 늦게라도 커밋해보겠습니다~!

**Comment by yelgit** [comment]
어렵다는거 엄살 아닌가요? 그래도 반응이 어제, 오늘 걱정하면서 고민한 보람은 있는거 같아 기분은 좋네요. 긍정적인 반응에 감사 드립니다.ㅋㅋㅋ

**Comment by ahryunPark** [comment]
난이도가 전혀 낮지 않습니다 책임님^^  예제도 많고 너무 좋네요~~
저도 우선 출첵하고 프로젝트 상황봐서 커밋하도록 하겠습니다!!

**Comment by youngmi-won** [comment]
머리 터지는줄...
근데 문제가 오른쪽에서 왼쪽으로 라고 되어 있어서 처음에 삽질을 좀 했네요.
왼쪽에서 오른쪽으로..... 가 맞지 않나요? (예제를 보면 그래 보입니다.)
제가 이해를 잘못한건가요 ㅠㅠ

**Comment by khbanhub** [comment]
한글은 쉬운데 작문은 영어로 해야하는 거죠.
일단 출석 좀 -.-;;;

**Comment by task-jslim** [comment]
문제 어렵습니다.^^; 시간 할애를 많이 했는데 못풀겠네요 
올려주신분 소스 보면서 공부하겠습니다.

**Comment by hrkim28** [comment]
출석....... 어렵습니다 : )

**Comment by cnsjunwoolee** [comment]
오늘도 12시 넘기면 행님 탓입니다.
