### ISSUE TITLE
10일차 문제(20190130)

### ISSUE THREAD

**Issue by jinkwui** [hrkim28/TCT#11]
> ### **문제**

2018년에 이어, 2019년에도 코드 몬스터가 개최된다!
코드 몬스터에서 빠질 수 없는 것은 바로 상금이다. 2018년에 개최된 제1회 코드 몬스터에서는, 본선 진출자 100명 중 21명에게 아래와 같은 기준으로 상금을 부여하였다.

순위	상금	인원
1등	500만원	1명
2등	300만원	2명
3등	200만원	3명
4등	50만원	4명
5등	30만원	5명
6등	10만원	6명

2019년에 개최될 제2회 코드 몬스터에서는 상금의 규모가 확대되어, 본선 진출자 64명 중 31명에게 아래와 같은 기준으로 상금을 부여할 예정이다.

순위	상금	인원
1등	512만원	1명
2등	256만원	2명
3등	128만원	4명
4등	64만원	8명
5등	32만원	16명

승우는 자신이 코드 몬스터에 출전하여 받을 수 있을 상금이 얼마인지 궁금해졌다. 그는 자신이 두 번의 코드 몬스터 본선 대회에서 얻을 수 있을 총 상금이 얼마인지 알아보기 위해, 상상력을 발휘하여 아래와 같은 가정을 하였다.
제1회 코드 몬스터 본선에 진출하여 a등(1 ≤ a ≤ 100)등을 하였다. 단, 진출하지 못했다면 a = 0으로 둔다.
제2회 코드 몬스터 본선에 진출하여 b등(1 ≤ b ≤ 64)등을 할 것이다. 단, 진출하지 못했다면 b = 0으로 둔다.
승우는 이러한 가정에 따라, 자신이 받을 수 있는 총 상금이 얼마인지를 알고 싶어한다.

>###  **2. 입력**

첫 번째 줄에 승우가 상상력을 발휘하여 가정한 횟수 T(1 ≤ T ≤ 1,000)가 주어진다.
다음 T개 줄에는 한 줄에 하나씩 승우가 해본 가정에 대한 정보가 주어진다. 각 줄에는 두 개의 음이 아닌 정수 a(0 ≤ a ≤ 100)와 b(0 ≤ b ≤ 64)가 공백 하나를 사이로 두고 주어진다.

> ### **3. 출력**

각 가정이 성립할 때 승우가 받을 상금을 원 단위의 정수로 한 줄에 하나씩 출력한다. 입력이 들어오는 순서대로 출력해야 한다.

> ### **4. 예제 입력**

6
8 4
13 19
8 10
18 18
8 25
13 16

> ### **5. 예제 출력**

1780000
620000
1140000
420000
820000
620000

**Comment by jinkwui** [comment]
다음 문제 출제자는 `박천희 책임님` 입니다. :)

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by choiswon** [comment]
빠르게 출석하고 문제 분석들어가봅니다...

**Comment by ximpley** [comment]
이 문제 어디서 봤는데.. ㅎㅎㅎ .. 푸시는 분은 어딘가에 입사시험 1차 패스하시겠네요....:-)

**Comment by youngmi-won** [comment]
출첵합니다. 오늘은 프로젝트에 일이 생겨서 제시간에 못풀겠네요. 저녁에나 해볼께요. ㅠㅠ

**Comment by ychanlim** [comment]
어제밤 Python으로 풀이하다 포기한 트라우마로 출첵부터 합니다.
문제볼때마다 느끼는거지만 개발언어보다 국어공부부터 해야겠어요.

**Comment by junwc** [comment]
출첵합니다. 금일 파이썬 리뷰어는 나태웅 선임입니다.

**Comment by yelgit** [comment]
출첵합니다. 문제는 읽어 보지만 거기까지네요.ㅠㅠ

**Comment by spica07** [comment]
출첵합니다.

**Comment by hjkimsky** [comment]
출첵합니다.

**Comment by khbanhub** [comment]
오늘은 잠시 김성모님의 도움을 받아 작성하신 몇분의 코드를 함께 읽어 보았습니다.
1. 코드를 간결하게 처리하거나 길게 나열하거나
2. 코드에 대한  Comment를 달거나 아무런 언급도 없거나

**Comment by ohardcore** [comment]
오늘 하루종일 회의라 저녁에 도전 해보겠습니다..
