### ISSUE TITLE
11일차 문제(20190131)

### ISSUE THREAD

**Issue by ultra1002** [hrkim28/TCT#12]
- 문제

알파벳 소문자로 이루어진 N개의 단어가 들어오면 아래와 같은 조건에 따라 정렬하는 프로그램을 작성하시오.

길이가 짧은 것부터
길이가 같으면 사전 순으로

- 입력

첫째 줄에 단어의 개수 N이 주어진다. (1≤N≤20,000) 둘째 줄부터 N개의 줄에 걸쳐 알파벳 소문자로 이루어진 단어가 한 줄에 하나씩 주어진다. 주어지는 문자열의 길이는 50을 넘지 않는다.

- 출력

조건에 따라 정렬하여 단어들을 출력한다. 단, 같은 단어가 여러 번 입력된 경우에는 한 번씩만 출력한다.

- 예제 입력

13
but
i
wont
hesitate
no
more
no
more
it
cannot
wait
im
yours

- 예제 출력

i
im
it
no
but
more
wait
wont
yours
cannot
hesitate

**Comment by ultra1002** [comment]
금일 고객과 점심식사 일정이 있어 문제 미리 올립니다. 양해부탁드립니다.

다음 출제자는 전우채 책임님입니다.

**Comment by choiswon** [comment]
회의가 있어서..출석하고 갑니다.

**Comment by ximpley** [comment]
와.. 단어 정렬 문제네요. 그둥안 수학에 머리아파 하던 분들 도전해보세요. 국어도 어렵진 않네요. 감사합니다.

**Comment by youngmi-won** [comment]
임용원 선임이랑 저는 고객회의로 금일 회의끝나고 참여하겠습니다~

**Comment by yelgit** [comment]
출첵합니다.
나도 이해 되는 문제가 왔네요. 그런데 코딩은 어렵다는거...언제쯤 나도 내손으로 작성한 코딩을 올릴 수 있을런지..^^;;

**Comment by ximpley** [comment]
의도를 가지고 코딩하시면 더 좋을 것 같습니다. 가장 단순한 로직의 경우.. , 가장 빠른 로직의 경우..
sort를 직접 구현하셔도 좋고, API를 이용해서 정렬을 한번에 처리할수 있어도 좋겠네요. 금일 힌트는 여기까지입니다.

**Comment by ximpley** [comment]
> 출첵합니다.
> 나도 이해 되는 문제가 왔네요. 그런데 코딩은 어렵다는거...언제쯤 나도 내손으로 작성한 코딩을 올릴 수 있을런지..^^;;

SQL로 짜셔도 됩니다.  :+1:

**Comment by yelgit** [comment]
아~~~^^

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by yelgit** [comment]
문제는 쉬운데, 저에겐 답이 어렵네요. 좀더 학습이 필요할 듯하네요. ㅜㅜ^^

**Comment by hjkimsky** [comment]
문제 확인

**Comment by junwc** [comment]
회의때문에 지금 출첵합니다. 금일 파이썬 리뷰어는 접니다.^^

**Comment by khbanhub** [comment]
일단은 우선 출첵부터 -.-;;;

**Comment by srjie** [comment]
ㅜㅜ
