### ISSUE TITLE
12일차 문제(20190211)

### ISSUE THREAD

**Issue by junwc** [hrkim28/TCT#13]
* 문제

스파이들은 사령부와 통신하기 위해서 SMTP(비밀 메시지 전송 프로토콜)를 사용해 비밀 회선으로 전자 메시지를 보낸다. 
메시지가 적들에 의해 조작되어 보내진 것이 아닌 진짜 메시지라는 것을 표시하기 위해 모든 메시지는 변형되는데, 이 변형 알고리즘은 메시지를 가로채는 자들이 우연히 변형 규칙을 흉내 낼 수 없을 정도로 정교하다. 
또한 요원들의 머리에 총구가 겨눠져 강제로 메시지를 말한 경우 간단히 실수를 의도적으로 넣어 이 메시지가 강제로 쓰인 메시지라는 것을 알려줄 수 있다.

알고리즘대로 정확하게 변형된 메시지는 각 문자가 세 번 등장할 때 한 번 더 문자가 삽입된다. 

예를 들면 요원이 "HELLOTHEREWELLBEFINE" 라는 메시지를 보내고 싶어 했다면 "HELLOTHEREEWELLLBEFINEE" 는 정확한 변형이다. 

몇 년 동안 이 메시지들의 진짜 여부는 고도로 훈련된 원숭이들이 판별해내었다. 그러나 사령부에 도착하는 메시지들의 양이 많이 늘어나면서 이 작업을 자동으로 처리해주는 프로그램을 고안하기로 하였다.

* 입력

첫째 줄에 100 이하의 테스트 케이스의 개수가 주어진다. 
그리고 각 테스트 케이스마다 대문자로만 이루어진 10만자 이하의 문자열 M이 한 줄에 주어진다. 
이 문자열은 검사해야할 메시지다.

* 출력

테스트 케이스마다 메시지 M이 진짜 메시지면 "OK"를, 가짜 메시지면 "FAKE"를 한 줄에 출력한다.

* 예제 입력

3
BAPC
AABA
ABCABCBBAAACC

* 예제 출력

OK
FAKE
OK

**Comment by junwc** [comment]
다음 출제자는 최상원 책임입니다.

**Comment by Kimsiwon75** [comment]
출석

**Comment by ximpley** [comment]
다들 새해 복 많이 받으세요. 3의 배수로 등장하는 경우가 없으면 되겠네요~. 오늘부터 김경희 책임님도 함께 하십니다.

**Comment by yelgit** [comment]
출첵합니다. 새해 복 많이 받으세요. 경희 책임 반가워. 잘 지냈지?!^^

**Comment by youngmi-won** [comment]
출첵합니다.

**Comment by choiswon** [comment]
출석합니다.

**Comment by junwc** [comment]
금일 파이썬 리뷰어는 최기훈 책임입니다.

**Comment by spica07** [comment]
출석합니다.

**Comment by ywlimx** [comment]
출석합니다.

**Comment by ahryunPark** [comment]
출석합니다

**Comment by jinkwui** [comment]
출석합니다.

**Comment by hjkimsky** [comment]
출석합니다.

**Comment by syeonoh** [comment]
혜령선임 저는 당부간 찾지 말아주세요... ㅠㅠ 자판 치기 좀많이 힘듭니다. ㅜ

**Comment by khbanhub** [comment]
늦었네요. 출석합니다.

**Comment by clamp83** [comment]
저도 출석체크합니다.
