### ISSUE TITLE
13일차 문제(20190212)

### ISSUE THREAD

**Issue by choiswon** [hrkim28/TCT#14]
[문제]
0부터 9까지의 숫자를 한 번만 사용하여 만든 숫자 중에 입력숫자(1≤ N ≤10,000,000,000)와 가장 차이가 적은 숫자를 출력한다. 
답이 여러 개일 경우, 더 작은 숫자를 출력한다.

---------- 예 시 ----------
[입력1]
222
[출력1]
219

[입력2]
5000
[출력2]
5012

**Comment by choiswon** [comment]
다음 출제자는 오승연 책임입니다.
-> 최기훈 책임으로 변경합니다.

**Comment by ximpley** [comment]
오승연 책임이 팔을 다쳐서 타이핑이 어려우니 다른 분으로 변경해주세요.

**Comment by hjkimsky** [comment]
출석체크합니다. workshop이후 확인하겠습니다.

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by ximpley** [comment]
일반적으로 푸시는 경우외에....한번만 사용하라는 명제를 이용하면 좀 엽기적인 로직도 나오겠네요. 
동일한 문제를 두번까지 사용해도 된다고 하면 또 문제가 완전히 달라지겠습니다. Range를 찾는 비슷한 문제가 G사 입사시험에 나온적 있던걸로 기억납니다.

**Comment by hrkim28** [comment]
출석합니다

**Comment by ohardcore** [comment]
출석입니다

**Comment by yelgit** [comment]
출첵합니다.

**Comment by junwc** [comment]
출첵합니다. 금일 파이썬 리뷰어는 김보미 책임입니다.

**Comment by tjdah13** [comment]
출석합니다

**Comment by hjna1987** [comment]
출석합니다!

**Comment by khbanhub** [comment]
출석합니다.
