### ISSUE TITLE
15일차 문제(20190214) - 패리티 행렬 검사법

### ISSUE THREAD

**Issue by youngmi-won** [hrkim28/TCT#16]
**[문제]**
패리티 검사법은 메시지를 주고받을 때 메시지가 패리티 성질을 가지고 있을 경우엔 메시지가 제대로 도착을 하였다 보고 그렇지 않을 경우 메시지가 제대로 도착을 하지 않았다고 판별을 하는 메시지 전송시의 오류 판별 및 교정을 하는 방법을 말한다.

불리언 행렬의 각각의 열과 각각의 행이 짝수 합을 가질 때 패리티 성질을 가지고 있다고 하자. 다시 말하자면 한 집합에 짝수개의 1이 있다는 이야기 이다.

아래는 패리티 성질을 가진 4 x 4의 행렬이다.
1 0 1 0
0 0 0 0 
1 1 1 1 
0 1 0 1
각각의 행의 합은 2, 0, 4, 2 이고 열의 합은 2, 2, 2, 2 이다.

당신이 할일은 행렬의 정보를 읽어서 이것이 패리티 성질을 가지고 있는지 없는지 판단해야한다. 만약 그렇지 않을 경우 하나의 비트를 바꿔서 이 행렬이 패리티 성질을 가질 수 있는가 확인하고 그렇지 않을 경우 행렬은 잘못된 행렬이라고 판단한다.

**[입력형식]**
첫줄에는 행렬의 크기인 n(n<100) 이 입력되며 n개의 줄에 n개의 0혹은 1이 입력된다.

**[출력형식]**
만약 행렬이 패리티 성질을 가질 경우 "OK"라 출력하고 하나의 비트만을 변경해서 패리티 성질을 가질 경우 바꿔야 될 비트가 있는 i행 j열 에 대해 "Change bit (i,j)" 라 출력하며 두 경우에 해당되지 않을 때는 "Corrupt"라고 출력한다.

* 주의 - 각각의 행과 열은 1부터 시작한다.

**[입력1]**
4
1 0 1 0
0 0 0 0
1 1 1 1
0 1 0 1
**[출력1]**
OK

**[입력2]**
4
1 0 1 0
0 0 1 0
1 1 1 1
0 1 0 1
**[출력2]**
Change bit (2,3)

**[입력3]**
4
1 0 1 0
0 1 1 0
1 1 1 1
0 1 0 1
**[출력3]**
Corrupt

※ 금일 발렌타인데이, 박아련 책임 생일, 제 휴직 기념 이벤트 진행합니다.
제일 먼저 정답을 올리신분께 스타벅스 아메리카노 기프티콘 쏩니다. ^^
고고~~

**Comment by hrkim28** [comment]
출첵합니다!

**Comment by spica07** [comment]
출첵합니다~

**Comment by tjdah13** [comment]
출석합니다~

**Comment by hrkim28** [comment]
재출석합니다

**Comment by khbanhub** [comment]
출석 합니다.

**Comment by ahryunPark** [comment]
출석합니다~ 책임님 생일 축하해주셔서 감사해요 ^^
복귀파티 준비하고 있겠습니다.(feat.닭갈비!! )

**Comment by youngmi-won** [comment]
다음 출제자는 이진경 총괄님 이십니다~

**Comment by junwc** [comment]
출석합니다.  파이썬 리뷰어는 홍세은 선임입니다.

**Comment by hjkimsky** [comment]
출석 합니다.

**Comment by kimkkhee** [comment]
출석함당~

**Comment by yelgit** [comment]
출첵합니다. 문제를 몇번씩 읽어야 내용을 이해하는 수준의 나에게는 무지 어려운 문제네요.ㅋ^^

**Comment by hjna1987** [comment]
출석체크 먼저 할게요 ㅎ

**Comment by ultra1002** [comment]
출첵합니다. 오늘은 오후 일이 많아 문제풀이가 힘들것 같습니다.
문제의 핵심은 Change bit를 찾아내는 것일것 같네요..

**Comment by srjie** [comment]
문제가 어려워서... 출첵으로 ㅜㅜ

**Comment by ywlimx** [comment]
출첵합니다. ㅜ.ㅜ

**Comment by cnsjunwoolee** [comment]
출첵합니다.

**Comment by ohardcore** [comment]
출석합니다.
