### ISSUE TITLE
16일차 문제(20190218) - 피보나치 수열

### ISSUE THREAD

**Issue by spica07** [hrkim28/TCT#17]
다음 소스는 N번째 피보나치 수를 구하는 C++ 함수이다.

int fibonacci(int n) {
    if (n == 0) {
        printf("0");
        return 0;
    } else if (n == 1) {
        printf("1");
        return 1;
    } else {
        return fibonacci(n‐1) + fibonacci(n‐2);
    }
}

fibonacci(3)을 호출하면 다음과 같은 일이 일어난다.

- fibonacci(3)은 fibonacci(2)와 fibonacci(1) (첫 번째 호출)을 호출한다.
- fibonacci(2)는 fibonacci(1) (두 번째 호출)과 fibonacci(0)을 호출한다.
- 두 번째 호출한 fibonacci(1)은 1을 출력하고 1을 리턴한다.
- fibonacci(0)은 0을 출력하고, 0을 리턴한다.
- fibonacci(2)는 fibonacci(1)과 fibonacci(0)의 결과를 얻고, 1을 리턴한다.
- 첫 번째 호출한 fibonacci(1)은 1을 출력하고, 1을 리턴한다.
- fibonacci(3)은 fibonacci(2)와 fibonacci(1)의 결과를 얻고, 2를 리턴한다.

1은 2번 출력되고, 0은 1번 출력된다. N이 주어졌을 때, fibonacci(N)을 호출했을 때, 0과 1이 각각 몇 번 출력되는지 구하는 프로그램을 작성하시오.

< 입력 >
첫째 줄에 테스트 케이스의 개수 T가 주어진다.
각 테스트 케이스는 한 줄로 이루어져 있고, N이 주어진다. N은 40보다 작거나 같은 자연수 또는 0이다.

< 입력 예제>
3
0
1
3
< 출력 예제 >
1 0
0 1
1 2

다음 출제자 분은 박아련책임님입니다.

**Comment by cherrylime** [comment]
오늘은 이슈가 좀 있어서 해 볼 수 있을랑가 모르겠네요..

**Comment by jinkwui** [comment]
출석체크 합니다. 인수인계가 있어서 시간 날 때 풀게요~

**Comment by hjna1987** [comment]
출석체크 합니다. 저도 1시부터 인수인계 일정이 있어서 회의 이후에 제출하겠습니다 ^^

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by choiswon** [comment]
출석체크합니다.

**Comment by hjkimsky** [comment]
우선 출석체크합니다.

**Comment by junwc** [comment]
출석체크합니다. 금일 파이썬 리뷰어는 김진귀 선임입니다.

**Comment by ohardcore** [comment]
출석합니다.

**Comment by ahryunPark** [comment]
출석체크합니다

**Comment by BBOMS** [comment]
저도 출석체크요!

**Comment by hrkim28** [comment]
출석합니다

**Comment by hseo-lee** [comment]
출석이요.

**Comment by yelgit** [comment]
오늘은 늦었네요. 일단 출첵하고 문제는 오후에 보도록 하겠습니다.

**Comment by srjie** [comment]
오늘은 업무가 너무 많아서. ㅜㅜ ... 출첵으로...

**Comment by khbanhub** [comment]
오창출장으로 늦었네요. 이제야 출석합니다 -.-;;;

**Comment by kimkkhee** [comment]
출석함당

**Comment by cnsjunwoolee** [comment]
마곡출장으로 일단 출첵만 합니다.

**Comment by ywlimx** [comment]
출석합니다.

**Comment by clamp83** [comment]
출석합니다.
