### ISSUE TITLE
17일차 문제(20190219) - 파일명 정렬

### ISSUE THREAD

**Issue by ahryunPark** [hrkim28/TCT#18]
**문제**
LG CNS에 입사한 지용이에게 선배는 팀 파일 서버를 알려주였다. 
파일서버에 있는 파일명 Rule이 정해져 있지 않아 이름 순으로 정렬시 보기가 불편하였다.
특히 숫자가 포함된 파일 목록은 여러 면에서 관리하기 불편했다. 
예컨대 파일 목록이 [“img12.png”, “img10.png”, “img2.png”, “img1.png”]일 경우, 일반적인 정렬은 [“img1.png”, “img10.png”, “img12.png”, “img2.png”] 순이 되지만, 
숫자 순으로 정렬된 [“img1.png”, “img2.png”, “img10.png”, img12.png”] 순이 정확하기 때문이다.

지용이는 파일명에 포함된 숫자를 반영한 정렬 기능을 저장소 관리 프로그램에 구현하기로 했다.
파일서버 저장된 파일명은 100 글자 이내로, 영문 대소문자, 숫자, 공백(“ “), 마침표(“.”), 빼기 부호(“-“)만으로 이루어져 있다. 파일명은 영문자로 시작하며, 숫자를 하나 이상 포함하고 있다.

파일명은 크게 HEAD, NUMBER, TAIL의 세 부분으로 구성된다.
 - HEAD는 숫자가 아닌 문자로 이루어져 있으며, 최소한 한 글자 이상이다.
 - NUMBER는 한 글자에서 최대 네 글자 사이의 연속된 숫자로 이루어져 있으며, 앞쪽에 0이 올 수 있다. 0부터 9999 사이의 숫자로, 000이나 0101 등도 가능하다.
 - TAIL은 그 나머지 부분으로, 여기에는 숫자가 다시 나타날 수도 있으며, 아무 글자도 없을 수 있다.
![image](https://user-images.githubusercontent.com/39943602/52987723-ac4fb680-343f-11e9-934f-16fd8c827a72.png)

**제한사항**
파일명을 세 부분으로 나눈 후, 다음 기준에 따라 파일명을 정렬한다.
 - 파일명은 우선 HEAD 부분을 기준으로 사전 순으로 정렬한다. 이때, 문자열 비교 시 대소문자 구분을 하지 않는다. CNS와 cns, CnS는 정렬 시에 같은 순서로 취급된다.
 - 파일명의 HEAD 부분이 대소문자 차이 외에는 같을 경우, NUMBER의 숫자 순으로 정렬한다. 9 < 10 < 0011 < 012 < 13 < 014 순으로 정렬된다. 숫자 앞의 0은 무시되며, 023와 23는 정렬 시에 같은 같은 값으로 처리된다.
 - 두 파일의 HEAD 부분과, NUMBER의 숫자도 같을 경우, 원래 입력에 주어진 순서를 유지한다. CNS01.zip과 cns1.png가 입력으로 들어오면, 정렬 후에도 입력 시 주어진 두 파일의 순서가 바뀌어서는 안 된다.

파일명 정렬 프로그램을 구현하라.

입력 형식

입력으로 배열 files가 주어진다.
 - files는 1000 개 이하의 파일명을 포함하는 문자열 배열이다.
 - 각 파일명은 100 글자 이하 길이로, 영문 대소문자, 숫자, 공백(“ “), 마침표(“.”), 빼기 부호(“-“)만으로 이루어져 있다. 파일명은 영문자로 시작하며, 숫자를 하나 이상 포함하고 있다.
 - 중복된 파일명은 없으나, 대소문자나 숫자 앞부분의 0 차이가 있는 경우는 함께 주어질 수 있다. (cns1.txt, CNS1.txt, cns001.txt, cns1.TXT는 함께 입력으로 주어질 수 있다.)

출력 형식

위 기준에 따라 정렬된 배열을 출력한다.

입출력 예제

입력: [“img12.png”, “img10.png”, “img02.png”, “img1.png”, “IMG01.GIF”, “img2.JPG”]
출력: [“img1.png”, “IMG01.GIF”, “img02.png”, “img2.JPG”, “img10.png”, “img12.png”]

입력: [“F-5 Freedom Fighter”, “B-50 Superfortress”, “A-10 Thunderbolt II”, “F-14 Tomcat”]
출력: [“A-10 Thunderbolt II”, “B-50 Superfortress”, “F-5 Freedom Fighter”, “F-14 Tomcat”]

**Comment by ahryunPark** [comment]
TCT 문제에 Sorting문제가 항상 나오는 것 같아서 유사문제를 찾아보았습니다.
다음 출제자는 김경희책임님 입니다

**Comment by tjdah13** [comment]
출석합니다

**Comment by hrkim28** [comment]
출석합니다. 회의로 저녁에 해보겠습니다

**Comment by ychanlim** [comment]
문제 잘 읽었습니다. 어떻게 지지고 볶아야할지 어렵네요 -..-;;

**Comment by ywlimx** [comment]
출석합니다.

**Comment by ohardcore** [comment]
출석합니다.

**Comment by spica07** [comment]
출석합니다.

**Comment by ximpley** [comment]
정렬, 탐색 두가지는 다양한 문제를 겪어보시면 좋겠습니다. map, reduce, filter 점점 중요해 질겁니다.

**Comment by junwc** [comment]
출석합니다. 파이썬 리뷰어는 나태웅 선임입니다.

**Comment by ckh80** [comment]
출석합니다.~

**Comment by yelgit** [comment]
출첵합니다. 어제는 문제 읽고 이해하는데 시간이 많이 걸렸는데...오늘은 읽을 량이 많지만 구현해야 될 로직이 어렵네요. ㅠㅠ

**Comment by BBOMS** [comment]
오 진짜 TCT문제유형이랑 비슷하네요 +1:

**Comment by BBOMS** [comment]
오 진짜 TCT 문제 유형과 비슷하네요 :+1:

**Comment by kimkkhee** [comment]
출첵함당~

**Comment by cnsjunwoolee** [comment]
30분만에 풀기는 어려울듯 하네요.  LPAD 문제인줄 알았는데 더 들어가야 겠네요.

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by choiswon** [comment]
출석합니다

**Comment by srjie** [comment]
오늘도 출첵 ^^

**Comment by hjkimsky** [comment]
회의로 출석체크합니다.

**Comment by khbanhub** [comment]
웬종일 미팅이 많았네요. 이제사 출석합니다.
참 문제가  참 Detail 하네요 ㅎ

**Comment by ultra1002** [comment]
출첵합니다. 도전적인 문제네요

**Comment by clamp83** [comment]
출석합니다.
