### ISSUE TITLE
18일차 문제(20190220) - 주어진 수열 중 가장 큰 합 구하기

### ISSUE THREAD

**Issue by kimkkhee** [hrkim28/TCT#19]
* 문제
 
n개의 정수로 이루어진 임의의 수열이 주어진다. 
우리는 이 중 연속된 몇 개의 수를 선택해서 구할 수 있는 합 중 가장 큰 합을 구하려고 한다. 
단, 수는 한 개 이상 선택해야 한다.

예를 들어서 10, -4, 3, 1, 5, 6, -35, 12, 21, -1 이라는 수열이 주어졌다고 하자. 
여기서 정답은 12+21인 33이 정답이 된다.

* 입력
 
첫째 줄에 정수 n(1 ≤ n ≤ 100,000)이 주어지고 둘째 줄에는 n개의 정수로 이루어진 수열이 주어진다. 
수는 -1,000보다 크거나 같고, 1,000보다 작거나 같은 정수이다.

* 출력
 
첫째 줄에 답을 출력한다.

* 예제 입력 
10
10 -4 3 1 5 6 -35 12 21 -1

* 예제 출력 
33

다음 출제자분은 이준우 책임님 입니다.

**Comment by hjkimsky** [comment]
문제만 확인합니다.급한 플젝 마무리건으로 바쁘네요..저녁에 도전해보겠습니다.

**Comment by ahryunPark** [comment]
출석체크합니다.

**Comment by junwc** [comment]
출석합니다. 금일 파이썬 리뷰는 제가 합니다.

**Comment by choiswon** [comment]
출석합니다.

**Comment by ohardcore** [comment]
출석합니다

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by khbanhub** [comment]
일단 오늘은 출석을 먼저....

**Comment by ximpley** [comment]
쉽지 않은 문제인데 다들 잘 푸셨나요?

**Comment by clamp83** [comment]
출석합니다.
