### ISSUE TITLE
19일차 문제(20190221)

### ISSUE THREAD

**Issue by tjdah13** [hrkim28/TCT#20]
00지하철 공사에서 지하철 운행중 차내에 타고있는 승객이 지불해야 하는 금액이 가장 큰 경우를 계산하는 프로그램을 의뢰 받았습니다.

(단구간 고객은 1000원, 환승 고객은 200원으로 계산, 모든 고객은 하차후 승차함, 최대정원 100명)

아래표는 각 역에서 승하차 하는 승객의 수를 표시한 표 입니다.

![image](https://user-images.githubusercontent.com/25019746/53142557-b2789b00-35d7-11e9-8d36-44328cc580b1.png)

풀이
2번역에서 운행시작 기준으로 단구간 인원이 42명 환승 인원 2명이 승차해 있으므로 42400원이 가장 많은 금액으로 집계됨

입력 

0 32 0 3
3 13 1 0
28 25 1 5
39 0 6 0

결과
42400

다음 출제자는 임영찬 책임님 입니다.

**Comment by cnsjunwoolee** [comment]
제 PC에서 문제 등록이 안되서 김성모 선임 PC에서 성모 선임 ID로 문제 등록 했습니다. (이준우 책임)

**Comment by choiswon** [comment]
출석 체크합니다.

**Comment by spica07** [comment]
출석체크합니다.

**Comment by Kimsiwon75** [comment]
출석

**Comment by hrkim28** [comment]
출석합니다!

**Comment by kimkkhee** [comment]
출석함당~

**Comment by ahryunPark** [comment]
출석합니다.

**Comment by ohardcore** [comment]
반영일이라.. 일단 출석 합니다.

**Comment by ckh80** [comment]
출석합니다.~

**Comment by hjna1987** [comment]
출석합니다.

**Comment by junwc** [comment]
출석합니다. 파이썬 리뷰어는 최기훈 책임입니다.

**Comment by jinkwui** [comment]
출석합니다. 시간 날때 풀겠습니다.^^

**Comment by ximpley** [comment]
생각보다 어려워 보이네요. 다들 잘 풀고 계시죠?.. 출석합니다.

**Comment by BBOMS** [comment]
아 저도 일단 늦었지만 출석이요

**Comment by ychanlim** [comment]
출석합니다.

**Comment by srjie** [comment]
ㅜㅜ

**Comment by hjkimsky** [comment]
늦게나마 출석체크합니다.오늘은 꼭 저녁에 도전~~

**Comment by yelgit** [comment]
어제는 미출석, 오늘은 늦게 출첵하네요.

**Comment by ywlimx** [comment]
출석합니다

**Comment by clamp83** [comment]
출석합니다.
