### ISSUE TITLE
20일차 문제(20190225) - 용돈 최대 금액

### ISSUE THREAD

**Issue by ychanlim** [hrkim28/TCT#21]
문제 : 아이가 가질 수 있는 최대 용돈의 금액은 얼마일까요?

엄마가 아이에게 용돈을 줍니다.
요즘 교과과정에 코딩교육이 들어간다고 하여 아이의 알고리즘 학습을 위해 용돈 주는 방법을 이용해 봅니다.

금액이 표시된 용돈 봉투 여러개를 원형으로 배열합니다. 
아이는 봉투 여러개를 선택 할 수 있지만 조건이 있습니다.
선택한 봉투 양쪽 옆의 봉투는 선택할 수 없습니다.

아래 예시는 원형을 배열로 표현한 것으로 첫번째 1000원과 마지막 5000원은 연속된 것으로 합니다.
1000원을 선택하면 양옆의 2000원과 5000원은 선택할 수 없습니다.
예시 : { 1000, 2000, 3000, 4000, 5000 }

예시로 주어진 배열에서 아이가 가질 수 있는 최대 금액을 구하세요.

[제약조건]
2 ~ 30 개의 배열 요소
배열의 요소는 1 ~ 50,000 사이의 값

[입력예시]
예시1 = { 2000, 3000 }
예시2 = { 1000, 3000, 1000 }
예시3 = { 2000, 2000, 2000, 2000 }
예시4 = { 1000, 10000, 8000, 5000, 7000, 3000, 9000 }

[출력예시]
결과1 = 3000
결과2 = 3000
결과3 = 4000  ( = 2000 + 2000 )
결과4 = 26000 ( = 10000 + 7000 + 9000 )

**Comment by tjdah13** [comment]
출석합니다

**Comment by ychanlim** [comment]
다음 출제자는 김보미 책임입니다.

**Comment by hjna1987** [comment]
현업회의가 있어서 일단 출석확인하고, 나중에 풀도록 하겠습니다.

**Comment by spica07** [comment]
출석합니다.

**Comment by ximpley** [comment]
재미있는 문제네요. 연속 배열... :-) 단순히 최대값을 찾고 양 옆수를 제외해 나가는 것 외에 어떤 방법이 있을까요?

**Comment by hrkim28** [comment]
출첵합니다

**Comment by ahryunPark** [comment]
출첵합니다~

**Comment by ckh80** [comment]
출석 체크합니다.~

**Comment by hjkimsky** [comment]
출첵합니다.~~~

**Comment by choiswon** [comment]
출석합니다

**Comment by yelgit** [comment]
출첵합니다. 로직만 생각해서 작성해 봤습니다. 아직 코딩까지 하긴 시간이 너무 짧네요.^^

**Comment by jinkwui** [comment]
출석합니다. 시간날때 풀겠습니다.

**Comment by BBOMS** [comment]
출석합니다~

**Comment by cnsjunwoolee** [comment]
어렵네요. 그냥 막 짜서 돌렸더니 안되네요. 그래도 일단 Commit 합니다. 나중에 수정할께요.

**Comment by ywlimx** [comment]
출책합니다~

**Comment by khbanhub** [comment]
마지막 답이 헷갈리네요. 음 돈가지고 이러면 애들이 싫어할듯 ㅋ
출첵이요

**Comment by Kimsiwon75** [comment]
출석합니다.

**Comment by kimkkhee** [comment]
출첵함당~

**Comment by junwc** [comment]
보고땜에 출석이 늦었습니다. 금일 파이썬 리뷰어는 김보미 책임입니다.
