### ISSUE TITLE
21일차 문제(20190226) - 휴대폰 고장난 자판

### ISSUE THREAD

**Issue by BBOMS** [hrkim28/TCT#22]
[문제]
메뚜기 재석이는 간만에 목초지에서 신났당. 무지무지 신났당. 너무너무 신나서 뛰어놀다가 그만!! 핸드폰을 물웅덩이에 빠뜨리고 말았다. 그 덕에 핸드폰은 젖어버렸고, 자판은 요상하게 작동한다. 

메뚜기 재석이는 고장난 자판이 뭐가 눌리는 건지 알아야 문자라도 보낼테니 재석이는 이것저것 눌러보기 시작했다. 메뚜기인 것도 서러운데 핸드폰까지 고장났으니 누군가의 도움이 필요할 것 같다.

이 그림은 핸드폰의 자판이다(안타깝게도 재석이는 메뚜기라 스마트폰을 사지 못 했다.). 예를 들어, a를 입력하고 싶으면 2를 한 번 누르면 되고, b를 입력하고 싶으면 2를 두 번 누르면 된다. 만약 똑같은 키를 연속해서 눌러 다른 문자를 입력하고 싶으면 #을 누르면 된다. 예를 들어, klor을 입력하고 싶으면 55#555666777을 눌러 입력하면 된다. 

<img width="150" alt="keyboard" src="https://user-images.githubusercontent.com/18729800/53383722-f2ff5c80-39bb-11e9-8b9a-b32c7e7ec7f6.png">

[입력]
첫째 줄엔 9개의 정수가 주어진다. 첫 번째 정수는 원래 자판에서 1을 눌렀을 때 나오는 문자가 어느 자판을 눌렀을 때 나오는지, 두 번째 정수는 원래 자판에서 2를 눌렀을 때 나오는 문자가 어느 자판을 눌러야 나오게 되었는지...이런 식이다. 

재석이는 *이랑 0은 쓸 수가 없다. #키는 망가지지 않았다.

두 번째 줄엔 소문자로 된 문자열이 주어진다. 길이는 100 문자를 넘지 않는다.

[출력]
재석이의 메세지를 쓰기 위해 눌러야 하는 키를 출력한다.

[예제입력1]
2 3 4 5 6 7 8 9 1
klor
[예제입력2]
7 8 9 1 2 3 6 5 4
djevojka
[예제입력3]
9 8 7 6 5 4 3 2 1
skakavac

[예제출력1]
44#444555666
[예제출력2]
68662227778#885
[예제출력3]
33335585582228#888

+) 다음 출제자는 소순원 책임입니다 :)

**Comment by spica07** [comment]
출석합니다..

**Comment by hjkimsky** [comment]
요사이 계속 출석만 하네요..오늘은 퇴근후에 도전해야할텐데요~~

**Comment by ychanlim** [comment]
출석합니다. 문제 읽을때는 시간안에 할 수 있을것 같은 희망이 ... 입력 부분을 보는 순간 그럼 그렇지. T..T

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by hrkim28** [comment]
출석합니다

**Comment by ahryunPark** [comment]
저도 재석이처럼 너무너무 신나고 싶습니다. 출석합니다!!

**Comment by ultra1002** [comment]
출석합니다. 어렵네요

**Comment by yelgit** [comment]
출첵 합니다. 오늘도 조금씩 나아가야 할텐데...재석이는 임재석 선임을 말하는거죠? 임선임 별명이 메뚜기??ㅋㅋㅋ

**Comment by jinkwui** [comment]
출석합니다.

**Comment by kimkkhee** [comment]
출첵함당~

**Comment by choiswon** [comment]
출석합니다.

**Comment by task-jslim** [comment]
제가 너무 신나서 그만..문제가 어려워진거 같습니다

**Comment by task-jslim** [comment]
제가 너무 신나서 그만..문제가 어려워진거 같습니다

**Comment by task-jslim** [comment]
제가 너무 신나서 그만..문제가 어려워진거 같습니다

**Comment by ximpley** [comment]
자판이 계속 바뀐다는 말인데.. 문제가 만만치 않아 보이네요..

**Comment by BBOMS** [comment]
중요한 걸 빼먹었네요 다음출제자는 소순원 책임입니다!

**Comment by junwc** [comment]
출석합니다. 파이썬 리뷰어는 임영찬 책임입니다.

**Comment by khbanhub** [comment]
출석합니다...

**Comment by ywlimx** [comment]
출석합니다
