### ISSUE TITLE
22일차 문제 (20190227)

### ISSUE THREAD

**Issue by ohardcore** [hrkim28/TCT#23]
### 문제
자연수 n 개로 이루어진 집합 중에 다음 두 조건을 만족하는 집합을 최고의 집합이라고 합니다.

각 원소의 합이 S가 되는 수의 집합
위 조건을 만족하면서 각 원소의 곱 이 최대가 되는 집합
예를 들어서 자연수 2개로 이루어진 집합 중 합이 9가 되는 집합은 다음과 같이 4개가 있습니다.
{ 1, 8 }, { 2, 7 }, { 3, 6 }, { 4, 5 }
그중 각 원소의 곱이 최대인 { 4, 5 }가 최고의 집합입니다.

집합의 원소의 개수 n과 모든 원소들의 합 s가 매개변수로 주어질 때, 최고의 집합을 return 하는 solution 함수를 완성해주세요.

### 제한 사항
최고의 집합은 오름차순으로 정렬된 1차원 배열(list, vector) 로 return 해주세요.
만약 최고의 집합이 존재하지 않는 경우에 크기가 1인 1차원 배열(list, vector) 에 -1 을 채워서 return 해주세요.
자연수의 개수 n은 1 이상 10,000 이하의 자연수입니다.
모든 원소들의 합 s는 1 이상, 100,000,000 이하의 자연수입니다.

### 입출력 예

|N          |S            |RESULT          |
|-----------|-------------|----------------|
|2			|9            |[4,5]           |
|2          |1            |[-1]            |
|3          |13			  |[4,4,5]		   |

다음 출제자는 김시원 책임님입니다.

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by choiswon** [comment]
출석합니다

**Comment by ximpley** [comment]
동적계획법인가요? 수분할 알고리즘 쓰는것보다 직관적으로 풀기가 더 쉬울것 같기도 하네요.

**Comment by yelgit** [comment]
출첵합니다. 고민만 하다 시간 다 가버렸네요. 오늘은 저녁에라도 함 도전해봐야겠네요.

**Comment by ychanlim** [comment]
출석합니다. 오늘 안에 풀 수 있길 ....

**Comment by jinkwui** [comment]
출석합니다.

**Comment by khbanhub** [comment]
출석입니다.

**Comment by kimkkhee** [comment]
출석함당

**Comment by junwc** [comment]
출석합니다. 파이썬 리뷰어는 홍세은 선임입니다.

**Comment by hjkimsky** [comment]
출석합니다.

**Comment by ximpley** [comment]
누군가는 수분할 알고리즘을 재귀호출 방식으로 풀기를 기대했는데 아쉽네요. 재귀호출 방식으로 풀어낸 후 해당 재귀호출 계산이 반복되지 않도록 최적화하면 어땠을까 합니다.

**Comment by ximpley** [comment]
분할 수의 곱이 분할될 갯수로 나누는게 최선이다라는 것이 사람의 직관이고 이게 로직에 들어가지 않은게 아쉽다는 이야기입니다. 수고하셨습니다.

**Comment by ximpley** [comment]
TCT 시험 보실때는 그냥 직관으로 푸세요. :+1:

**Comment by ywlimx** [comment]
출석합니다.
