### ISSUE TITLE
[★Front-End, EAD직군 필참★] 22일차 문제(20190227)

### ISSUE THREAD

**Issue by hrkim28** [hrkim28/TCT#24]
<h3>학습조직 FrontEnd / EAD직군이신 분들은 댓글로 답/이유를 등록해주시기 바랍니다.</h3>  
<hr/>  

**1. 아래 자바 스크립트 코드 중에서 콘솔 로그 결과가 올바르지 않는 것을 고르시오.**  ### _④_

①	
```
    {
        var a = 10;
        {
            let a = 20;
            console.log(a);
        }
        console.log(a);
    }	
    console.log(a);
```
결과 20
     10
     10

②	
```
    {
        var b = 10;
        {
            var b = 20;
            console.log(b);
        }
        console.log(b);
    }
    console.log(b);
```
결과 20
     20
     20

③	
```
    {
        let c= 10;
        {
            let c = 20;
            console.log(c);
        }
        console.log(c);
    }
    console.log(c);
```
결과 20
     10
     Uncaught ReferenceError: c is not defined 

④	
```
    {
        var d= 10;
        {
            console.log(d);
            let d = 20;
        }
        console.log(d);
    }
    console.log(d);
```
결과 10
     10
     10
 

```
[정답] 4번
[해설]
- 유형 : ES6 Block Scope, TDZ
ES6(ECMAScript2015) 변수 선언. var는 function-scope, const/let은 block-scope({})
let 재할당 가능/const 재할당 불가
4번 let, const Hoisting 가능한데 초기화 되기 전에 console.log 로 접근했으므로 
첫번째 console.log에서 ReferenceError 발생함
``` 
    
**2. 다음 중 예상 결과로 틀린 것은?**
```
<script type="text/javascript">
            $(document).ready(function() {
                $("#btn1").click(function() {
                    $("p").append("<b>Appended text</b>");
                });
                $("#btn2").click(function() {
                    $("p").prepend("<b>Prepend text</b>");
                });
                $("#btn3").click(function() {
                    $("<li>Appended item</li>").appendTo("ol");
                });
                $("#btn4").click(function() {
                    $("<li>Prepended item</li>").prependTo("ol");
                });
                $("#btn5").click(function() {
                    $("p").after("<p>Hello world !</p>");
                });
                $("#btn6").click(function() {
                    $("p").before("<p>Bye world !</p>");
                });
            })
</script>
<body>
        <p>This is one of javascript.</p>
        <p>I am developer.</p>
        <ol>
            <li>React JS</li>
            <li>Vue JS</li>
            <li>Angluar JS</li>
        </ol>
        <button id="btn1">Append</button>
        <button id="btn2">Prepend</button>
        <button id="btn3">AppendedTo</button>
        <button id="btn4">PrependedTo</button>
        <button id="btn5">After</button>
        <button id="btn6">Before</button>
</body>

```
① Append 버튼 클릭
    [결과]
    This is one of javascript.**Appended Text.**
    I am developer. **Appended Text.**
    1. React JS
    2. Vue JS
    3. Angular JS

② AppendedTo 버튼 클릭
[결과]
    This is one of javascript.
    I am developer.
    1. React JS
    2. Appended Item
    3. Vue JS
    4. Angular JS

③ PretendedTo 버튼 클릭
[결과]
    This is one of javascript.
    I am developer.
    1. Pretended Item
    2. React JS
    3. Vue JS
    4. Angular JS

④ Before 버튼 클릭
   [결과]
    Bye world !
This is one of javascript.
Bye world !
    I am developer. 
    1. React JS
    2. Vue JS
    3. Angular JS

```
[정답] 2번
[해설]
- 유형 : jQuery
ol 태그에서 마지막 자식 요소로 추가되어야 하므로 정상 수행되면 마지막 4번으로 추가된다.
.append(), .appendTo() 는 동일한 기능이나 타겟이 다르므로 주의!
   - A.append(B) : A에 B를 마지막 요소로 추가하는 것
   - A.appendTo(B) : B에 A를 마지막 요소로 추가하는 것
     (* prepend, prependTo 도 동일하게 해석하면 됨)

This is one of java-script.
I am developer.
   1. React JS
   2. Vue JS
   3. Angular JS
   4. Appended Item
``` 
  
**3. 다음 중 결과값이 다른 것을 고르시오.**
① 
```
function drawChart(conditions) {
    conditions = conditions === undefined ? {} : conditions;
    var size = conditions.size === undefined ? 'large' : conditions.size;
    var cords = conditions.cords === undefined ? { x: 0, y:0 } : conditions.cords;
    var radius = conditions.radius === undefined ? 15 : conditions.radius;
    console.log(size, cords, radius);
}
drawChart({
    cords: { x: 12, y: 20 },
    radius : 30
})
```
  
②  
```
function drawChart ({size = 'large', cords = { x: 0, y: 0 }, radius = 15} = {})  {
       console.log(size, cords, radius);
}
drawChart({
    cords: { x: 12, y: 20 },
    radius : 30
})
```

③ 
```
const drawChart = ({size, cords, radius}) => {
    cords = [{x: 0, y:0 }]
    console.log(size, cords, radius)
}
drawChart({size: 'large', cords:{x:12,y:20}, radius: 30});
```

④ 
```
const drawChart = (conditions) => {
    conditions = Object.assign({
        size : 'small',
        cords: {x:0, y:0},
        radius: 15
    }, conditions)
    console.log(conditions.size, conditions.cords, conditions.radius)
}
drawChart({size: 'large', cords:{x:12,y:20}, radius:30});
```

```
[정답] 3번
[해설]
​- 유형 : ES6 Default Parameter
- 동일한 값에 대해 변수로 받았으나 3번은 함수 내에서 cords를 재할당 {x:0, y:0} 하므로 출력된 값이 다르다. 나머지 결과값은 large {x:12,y:20} 30
[참고]
1. 1,2,4를 보시면 기본값을 세팅할 수 있음을 알 수 있다. 
  1번은 기본적으로 알고있는 것이고, 2,4번 ES6에서는 함수 선언 시 Default value 선언이 가능하다는 것을 알 수 있다.
2. 3,4번을 보면 ES6 Arrow Function 사용된 것을 볼 수 있다.
```

**Comment by spica07** [comment]
1. 4번은 결과 안나옴
    {
        var d= 10;
        {
            console.log(d); , <-- 여기서 에러
            let d = 20;
        }
        console.log(d);
    }
    console.log(d);

2. 2번
2번 결과는 아래일 듯
This is one of javascript.
I am developer.
1. React JS
2. Vue JS
3. Angular JS
4. Appended Item

3. 2번
size는 undefined가 아닐지???

function drawChart ({size = ‘large’, cords = { x: 0, y: 0 }, radius = 15} = {})  {
       console.log(size, cords, radius);
}
drawChart({
    cords: { x: 12, y: 20 },
    radius : 30
})

**Comment by tjdah13** [comment]
1번 : 4
-> 4번째 line console.log(d); 에서 오류 발생
block scope 내에서 let으로 선언된 변수 d가 변수는 hoisting됐지만 할당이 안돼서?


2번 : 2
-> Appended item 가 리스트의 마지막에 추가되어야 함

This is one of javascript.
I am developer.
1.React JS
2.Vue JS
3.Angluar JS
4.Appended item


3번 : 나중에 보겠습니다..

**Comment by ohardcore** [comment]
1. 4
TDZ 에 걸려서 변수 선언은 되었지만, 할당 되지 않은 d 값 때문에 console.log 에서 에러 발생.

2. 2
맨마지막에 붙어야 하는데 중간에 붙음.

3. 3
다른 애들은 값이 없을때 해당 값으로 변수 초기화
3번은 값을 무조건 0,0으로 교체 하여 다른 결과

**Comment by choiswon** [comment]
1. (4)
 --> 4번째 줄 console.log(d) 오류발생
     let으로 선언한 변수의 scope는 block scope인데 값이 선언되기 이전이라서

2. (2)
 --> AppendedTo는 마지막에 추가되어짐
This is one of javascript.
I am developer.
1. React JS
2. Vue JS
3. Angular JS
4. Appended Item

3. (3)
 --> 3번은 입력받은 값중에서 cords의 값은 무시하고 [{x: 0, y:0 }]로 출력함

**Comment by ultra1002** [comment]
1. 정답 4
   두번째 console.log(d); 에서 d is not defined 떨어질듯

2. 정답 2
  This is one of javascript.

	I am developer.
	1.React JS
	2.Vue JS
	3.Angluar JS
	4.Appended item
	
	맨 뒤에 추가 됨
	
3. 정답 3

 cords = [{x: 0, y:0 }] 명시적으로 값을 바꿔줘버림

**Comment by task-jslim** [comment]
1.4번 
let으로 선언되어 block-scope 변수로서의 기능을 수행 
hoisting을 허용하지 않다보니 에러가 발생하여 결과값가 다르게 나옵니다.
2.2번
 Appended Item이 맨밑으로 나와야 됨
3. 3,4번 const는 재할당이 안되기때문에 에러발생..
1,2번은 동일 결과값 출력

**Comment by hrkim28** [comment]
1. ④
 - let 변수는 block-scope로 Hoisting되서 TDZ에 빠지게 되므로 ReferenceError 발생함
2. ②
 - ol 태그에 li 태그 추가하는 것으로 가장 마지막으로 추가되어야 함
3. ③
 - 기본값 세팅되어 있고 변수로 받아 console로 출력하는 건인데,
    ③ 은 cords 부분을 다시 {x:0, y:0} 으로 할당하므로 출력값이 다름

**Comment by kimkkhee** [comment]
1, 4번
=> 변수 할당 이전에 로그 수행
2. 2번
=> 마지막 줄에 추가되어야 함
3. 3	번
=> cords값을 x:0, y:0으로 할당

**Comment by ximpley** [comment]
다들 열심히 하셨네요. ES2015 수강 완료 기념으로 문제풀이 해보았습니다. 수고하셨습니다. :100:

**Comment by hseo-lee** [comment]
1. ④ 마지막 console.log 는 let으로 선언한 변수라 ReferenceError
2. ② 2. Appended Item가 맨 아래로 
3. ③ 다수결

**Comment by jinkwui** [comment]
1. ④
  제일 안쪽 d가 선언이 안되었다고 나올 것 같네요.
2. ②
   li 의 맨 마지막에 추가 되어야 할 것 같네요.  
3. 아직 ES2015 수강을 못해서 문법 공부좀 더해야할 것 같아요.ㅜ

**Comment by ywlimx** [comment]
1. (4)
선언되기전에 사용되었으므로  첫번째 console.log(d); 에서 error 발생, 

2.  ... ㅜㅜ

3. (3)
새로 할당된 [{x: 0, y:0 }] 출력
