### ISSUE TITLE
23일차 문제(20190228) - 데이트 상대/기억력/위험도 산출

### ISSUE THREAD

**Issue by Kimsiwon75** [hrkim28/TCT#25]
### 문제
결혼 적령기인 LG CNS 모 책임은 동시에 여러명의 상대를 소개받아 데이트를 하게 되었습니다.
그러나 모 책임은 상대적으로 기억력이 좋지 않아 상대방이 많아질수록 실수를 하게 될 Risk가 증가하게됩니다.
모 책임을 위해 모 책임의 기억력에 따른 위험도를 산출하는 프로그램을 작성해야 합니다.

### 제한 사항
1. 입력 형식
   . 모 책임의 기억력 사이즈와 데이트하는 상대의 이름 배열을 입력받습니다.
   . 기억력 사이즈는 정수이며 범위는 0 이상 10 이하입니다.
   . 상대방의 이름은 문자열 배열로 최대 100개입니다.

2. 출력 형식
   . 입력된 상대의 이름을 순서대로 만날때 실수를 하게될 위험도를 출력합니다.

3. 조건
   . 기억력은 가장 최근에 만나 사람을 기억합니다.(Least Recently Used)
   . 기억력 범위 안일 경우 위험도는 1 증가합니다.
   . 기억력 범위 밖일 경우 위험도는 5 증가합니다.

### 입출력 예
1. 예제 1
(1) 입력
   . 기억력: 3
   . 상대: ["전지현", "손예진", "송혜교", "수지", "설현", "전지현", "손예진", "송혜교", "수진", "설현"]
(2) 출력
   . 위험도: 50

2. 예제 2
(1) 입력
   . 기억력: 3
   . 상대: ["전지현", "손예진", "송혜교", "전지현", "손예진", "송혜교", "전지현", "손예진", "송혜교"]
(2) 출력
   . 위험도: 21

3. 예제 3
(1) 입력
   . 기억력: 2
   . 상대: ["전지현", "손예진", "송혜교", "수지", "설현", "김하늘", "송혜교", "이나영", "한가인", "전지현", "수지", "이나영"]
(2) 출력
   . 위험도: 60

3. 예제 4
(1) 입력
   . 기억력: 5
   . 상대: ["전지현", "손예진", "송혜교", "수지", "설현", "김하늘", "송혜교", "이나영", "한가인", "전지현", "수지", "이나영"]
(2) 출력
   . 위험도: 52

다음 출제자는 최정수 책임님입니다.

**Comment by srjie** [comment]
손예진 1표 ^^

**Comment by choiswon** [comment]
출석합니다

**Comment by Kimsiwon75** [comment]
저도 개인적으로 손예진을 최애합니다.

**Comment by yelgit** [comment]
출첵합니다. 일단 결혼 적령기에 든 모 책임은 남자였네요.^^ 문제의 패턴을 이해 못하네요. 쩝

**Comment by hjkimsky** [comment]
출첵입니다..

**Comment by Kimsiwon75** [comment]
제 국어 실력이 딸려서 많은 분들이 이해를 못하는 것 같네요. Cache 문제입니다. Cache에 데이터 저장되어 있으면 조회하는데 1초, 없으면 5초 소요되고 Cache는 항상 최신 n개만 저장되는 형태입니다.

**Comment by khbanhub** [comment]
오늘은 출석만 먼저합니다 -.-;;

**Comment by ohardcore** [comment]
출석합니다.

**Comment by junwc** [comment]
출석합니다. 파이썬 리뷰어는 나태웅 선임입니다.

**Comment by ywlimx** [comment]
출석합니다.

**Comment by cnsjunwoolee** [comment]
출첵입니다.

**Comment by ximpley** [comment]
문제가 물어보는 의도를 한참 생각했습니다. 아무튼 만난 사람들을 기억력 사이즈만큼 Cache 하는 걸로 하고, 연속된 데이트마다 Cache와 소요시간을 누적하라는 걸로 보입니다. 뒤늦었지만 다들 참고하세요.

**Comment by ximpley** [comment]
접근방법은 기억력 사이즈만큼의 앞 이벤트에 이번에 만나는 사람이 있는지 체크해서 위험도를 증가시키는 단순 접근방법과, Cache 데이터 구조를 만들고 핸들링하는 방법 2가지가 있겠네요. 위험도가 매 이벤트마다 모든 사람에게 변경되는 동시성 문제로 생각하면 어떨까 하고 생각이 드네요. 아무튼 출제하느라 수고하셨습니다.
