### ISSUE TITLE
[★Front-End, EAD직군 필참★] 23일차 문제(20190228)

### ISSUE THREAD

**Issue by hrkim28** [hrkim28/TCT#26]
<h3>학습조직 FrontEnd / EAD직군이신 분들은 댓글로 답/이유를 등록해주시기 바랍니다.</h3>  
<hr/>  

**1. 다음의 소스를 보고 예상되는 결과가 올바른 것을 고르시오.**

[javascript]
```
2.	function color (p) {
3.	  console.log(v) 
4.	  if (p) {
5.	    var v = 'blue'
6.	    console.log(v)
7.	  } else {
8.	    var v = 'red'
9.	    console.log(v)
10.	  }
11.	  console.log(v)
12.	}
13.	color(10) 
```

①	undefined, blue, blue
②	reference Error, blue, blue
③	10, blue, red
④	reference, blue, red

```
[정답] 1번
[해설]
​- 유형 : ES6 Scope
- var변수는 function scope 이므로 호이스팅 되어서 var변수가 선언되기 전에 접근하여도 undefined로 출력된다. 
만약 const, let 으로 선언되었다면 ReferenceError: a is not defined 발생한다.
``` 
<hr/>

**2. 다음 소스에 대한 결과를 입력하시오.**  
```
for (var i = 0; i < 9; i++) {
  setTimeout(function() {
    console.log(i);
  }, i * 100);
}
```

```
[정답] 9가 9번 출력됨
[해설]
​- 유형 : 클로저(Closure)
​- 0.1초 후 호출하기까지 이미 i는 9가 되어 있고 setTimeout은 내부함수로 외부함수인 상위 i를 참조하게 된다.
​  따라서 이미 9가 된 i를 9번 출력하게 된다.
​- 참고) https://meetup.toast.com/posts/86
```

**Comment by tjdah13** [comment]
1번 : 1
-> ① undefined, blue, blue

가 : 값할당이 안되어 있음
나 : true 로직을 타기 때문에 변수v에 blue값 할당
다 : 변수가 함수 내에서 Hoisting

2번 : 9가 9번출력
-> 함수 timeout인 100ms 동안 반복문이 모두 수행되어 변수 i의 값이 9로 출력 됨(?)
내부함수 에서 외부 변수를 참조 함?

**Comment by choiswon** [comment]
1. ① undefined, blue, blue
1번째 console.log : v에 대한 선언이 없으므로, undefined
2번째 console.log : if조건절의 p에 10의 값이 와서 True이므로 로직이 수행되면서 blue
3번째 console.log : 로직 미수행
4번째 console.log : if조건절의 True수행으로 v에 blue 값이 할당되어 blue
그런데, (가)(나)(다)는 왜 있는건지???

2, console.log가 100ms 간격으로 9번 수행되는데, 
for문상에 i값이 9까지는 할당이 되고 break되는데
그때 값이 9가 되므로 9가 9번 출력됨
9
9
9
9
9
9
9
9
9

**Comment by task-jslim** [comment]
1. 1번 
1번째 : v -> 값 설정이 안되어 있음
2번째 : p가 10으로 True 타서 blue 탐
3번쨰 : 미수행
4번째 blue
2. 9가 9번 출력 
-> i*100 -> i가 9로 할당되서 실행?

**Comment by ultra1002** [comment]
1. 정답 1
   undefined, blue, blue
   var의 장점이자 단점인듯...

2. 정답 : 9가 9번 찍힘
   테스트 해보니 9가 9번찍히긴 하는데 안돌려보면 잘 모르겠네요
   100ms timeout 기다리는 동안 i 인덱스는 일단 9까지 증가해버려서
   마지막 9가 9번찍히는듯...

**Comment by ohardcore** [comment]
1 번 ①	undefined, blue, blue
v가 선언되어 있지 않기 때문에 undefined error 발생 

2 번 999999999 가 찍힌다.
timeout 이 되는동안 9가 되어 9로 발생함.
timeout을 제거해야 1~ 8까지 찍힘.

**Comment by jinkwui** [comment]
1. ①	undefined, blue, blue
  (가) v 값에 값이 없어서 undefined.

2. 9가 9번 출력됨.
   settimeout은 실행되고 있는 함수 가 끝난 후에 실행되기 때문에... i=9가 아닐까 생각됩니다.

**Comment by hrkim28** [comment]
1.  ①  
-> var 변수는 function scope 이므로 호이스팅 되어서 var 변수가 선언되기 전에 접근하여도 undefined값이 출력됨.

2. 9 9 9 9 9 9 9 9 9
-> setTimeOut의 내부함수에서 i를 쓰는데 해당 값은 이미 수행된 for문의 i를 사용함.
     따라서 9를 9번 찍게 됨

**Comment by ximpley** [comment]
다들 잘 하셨네요. 낮에 봤을 때 기호가 있어서 이상했는데 문제가 수정되었습니다. 그리고 2번 같은 이유로 setTimeOut은 버그 유발이 심해서 권장되지 않습니다.
