### ISSUE TITLE
24일차 문제(20190304) - 회문(Palindrome)

### ISSUE THREAD

**Issue by ychanlim** [hrkim28/TCT#28]
[문제]
회문(回文, palindrome)이란 "madam이나 nurses run처럼 앞에서부터 읽으나 뒤에서부터 읽으나 동일한 단어나 구"를 말합니다.

문자열에 0개 이상의 문자를 추가해 회문을 생성할때,
가장 짧은 길이의 회문을 구하기 위해 필요한 중복을 제외한 문자의 갯수를 구하시오.

[제한사항]
영어 소문자 (a ~ z)로 구성된 1 ~ 50 글자의 문자열

입력예시 : madam
출력예시 : 0  (madam 자체가 회문)

입력예시 : abab
출력예시 : 1 ( = a)

입력예시 : lalavla
출력예시 : 3 ( = a, v, l)

* 다음 출제자는 김희정 책임님입니다.

**Comment by ychanlim** [comment]
최정수 책임님이 출장이셔서 대리 등록합니다.

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by srjie** [comment]
문제가 이해가 안되서 ... ㅜㅜ... 출첵 ^^

**Comment by Kimsiwon75** [comment]
3번째 예시 잘못된 거 아닌가요?

**Comment by yelgit** [comment]
출첵합니다. 문제는 이해했어요. 3번 문제 이해하는데 오래걸렸네요. 로직이 구현이 안되네요. 퇴근 후에도 좀더 고민해봐야겠네요.

**Comment by ychanlim** [comment]
3번 예시는 아래와 같습니다. 
lalavla 를 회문을 만들려면 lalavla + lvalal = lalavlalvalal  그래서 a, v, l 세자가 필요한 것입니다.

**Comment by spica07** [comment]
출석합니다.

**Comment by hjna1987** [comment]
출석!

**Comment by ahryunPark** [comment]
출석합니다~

**Comment by khbanhub** [comment]
출석합니다. 금주는 출장이 잦아 제대로 출석할수 있으려나 걱정이 ...

**Comment by hjkimsky** [comment]
우선.. 출석!!!

**Comment by jinkwui** [comment]
출석합니다.

**Comment by junwc** [comment]
출석합니다. 파이썬 리뷰어는 김진귀 선임입니다.

**Comment by ohardcore** [comment]
출석합니다.. 문제가 좀 헷갈리네요

**Comment by cnsjunwoolee** [comment]
서울 출장으로 일단 출첵만 합니다.
