### ISSUE TITLE
25일차 문제(20190305) - 진수

### ISSUE THREAD

**Issue by hjkimsky** [hrkim28/TCT#29]
[문제]
10진수에서 3 또는 9의 배수로 만들어진 숫자는 각 자릿수의 합도 3 또는 9의 배수가 됩니다.(아셨나요?^^)
예를 들어 354는 118*3=354로 3의 배수이자 3+5+4=12 로 12 역시 3의 배수입니다.
9의 배수 972는 108*9=972로 9의 배수이자 9+7+2=18로 18 역시 9의 배수입니다.
(2 또는 5의배수인 100은 2와5의배수는 만족하지만, 1+0+0=1이 되므로 합계가 2 또는 5의 배수가 안 됩니다.)

3진수에서 숫자 2가 이런 성질을 가지고 있습니다.
예를 들어 10진수 6을 3진수로 표현하면 20이고 2+0=2 로 2의 배수입니다.
10진수 26을 3진수로 표현하면 222이고 2+2+2=6으로 2의 배수입니다.

입력값으로 진수가 주어졌을때 위와 같은 성질을 가지는 숫자를 모두 출력하세요. (단, 0과 1은 제외함)
어떤 수가 이러한 합의 배수가 되는 성질을 가지는지 알고자 모든 숫자의 곱을 고려할 필요는 없습니다.
만약 4자리 미만의 곱으로 성립되면 더 큰 자리에서도 성립된다고 할 수 있습니다.
(예를 들어 10진수에서는 999보다 큰숫자를 고려하지 않아도 됩니다.)

[제한사항]
진수(base) : 3~30까지의 정수

[입출력]
입력예시 : 진수 = 10
출력예시 : 3,9

입력예시 : 진수 = 3
출력예시 : 2

입력예시 : 진수 = 26
출력예시 : 5, 25

입력예시 : 진수 = 30
출력예시 : 29

**Comment by hjkimsky** [comment]
다음 출제자는 지승룡책임 입니다.

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by cnsjunwoolee** [comment]
10진수에서 끝났으면 좋았을 텐데... 일단 출첵

**Comment by ywlimx** [comment]
출석합니다

**Comment by ahryunPark** [comment]
출석합니다

**Comment by junwc** [comment]
출석합니다. 파이썬 리뷰어는 제 차례입니다.

**Comment by hrkim28** [comment]
출석합니다.

**Comment by ckh80** [comment]
출석체크 합니다.

**Comment by srjie** [comment]
내일 출제 준비를 위해서...오늘은 출첵만 ^^

**Comment by tjdah13** [comment]
출석합니다

**Comment by yelgit** [comment]
출첵합니다. 오늘은 앞선 SQL 문제 공부하느라 시간을 다 써버렸네요. 이문제는 오후로 패쑤~~

**Comment by choiswon** [comment]
출석합니다

**Comment by spica07** [comment]
출석합니다

**Comment by hjkimsky** [comment]
출제자이지만,, 문제풀이는 안해봤어요... 오늘 해봐야 겠네요~~

**Comment by kimkkhee** [comment]
출석함다

**Comment by khbanhub** [comment]
출첵입니다

**Comment by ximpley** [comment]
16진수는 어찌되나요.. 10진수 이하는 대충 그려지는데.. 29진수, 30진수는 우선 오프라인으로 잘 안그려지네요.. 수고하셨습니다.
