### ISSUE TITLE
26일차 문제 (20190306) - Java/C 변수명 치환

### ISSUE THREAD

**Issue by srjie** [hrkim28/TCT#32]
[문제]
 Java에서는 변수의 이름이 여러 단어로 이루어져있을 때, 다음과 같은 방법으로 변수명을 짓는다. 
첫 단어는 소문자로 쓰고, 다음 단어부터는 첫 문자만 대문자로 쓴다. 또, 모든 단어는 붙여쓴다. 따라서 Java의 변수명은 javaIdentifier, longAndMnemonicIdentifier, name과 같은 형태이다.
반면에 C++에서는 변수명에 소문자만 사용한다. 
단어와 단어를 구분하기 위해서 밑줄('_')을 이용한다. C++ 변수명은 c_identifier, long_and_mnemonic_identifier, name 과 같은 형태이다.

C++형식의 변수명을 Java형식의 변수명으로, 또는 그 반대로 바꿔주는 프로그램을 만들려고 한다. 각 언어의 변수명 형식의 위의 설명을 따라야 한다.
만약 C++형식과 Java형식 둘 다 아니라면, 에러를 발생시킨다. 변수명을 변환할 때, 단어의 순서는 유지되어야 한다.

[입력 예1]
long_and_mnemonic_identifier

[출력 예1]
longAndMnemonicIdentifier

[입력 예2]
jobLog

[출력 예2]
job_log

**Comment by srjie** [comment]
다음 출제자는 오승연 책임입니다. 이제 키보드 칠 수 있다고 합니다. ^^

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by yelgit** [comment]
출첵합니다. 이 문제는 꼭 오늘 내로 풀어서 올려보도록 하겠습니다.^^

**Comment by ychanlim** [comment]
쉬운 문제죠? 오늘은 GG 안하고 싶습니다.

**Comment by junwc** [comment]
출석합니다. 파이썬 리뷰어는 최기훈 책임입니다.

**Comment by srjie** [comment]
GG

**Comment by spica07** [comment]
출석합니다

**Comment by ximpley** [comment]
이제 막 만들어진 것 같은 따끈한 문제네요. 수고하셨습니다.

**Comment by khbanhub** [comment]
코드 정적분석 도구로 쓰면 되는감요?
출석합니데이

**Comment by cnsjunwoolee** [comment]
오랜만에 도전해 볼만한 문제가 나왔네요.

**Comment by hjkimsky** [comment]
외부 회의다녀와서 이제서야 출석만 합니다.

**Comment by task-jslim** [comment]
오늘 출석 먼저 찍습니다.

**Comment by task-jslim** [comment]
오늘 출석 먼저 찍습니다.

**Comment by ywlimx** [comment]
출석합니다
