### ISSUE TITLE
28일차 문제(20190311) - 괄호 짝 맞추기

### ISSUE THREAD

**Issue by cherrylime** [hrkim28/TCT#34]
**[문제]**
3 종류의 괄호문자들 '()', '[]', '{}' 로 이루어진 문자열이 주어진다.
이 문자열에 사용된 괄호들의 짝이 모두 맞는지 판별하는 프로그램을 작성한다.
예를 들어 아래와 같은 문자열은 유효하다고 판단할 수 있다.

{[()]}[{}]

아래와 같은 문자열은 유효하지 않은 문자열이다. '[' 괄호의 짝을 찾을 수 없기 때문이다
{[()]}[{}

아래 문자열은 열고 닫는 괄호의 개수는 유효하나 짝이 맞지 않는 괄호가 사용 되었기 때문에 유효하지 않다 ==> {)
{[()]}[{)]

**[입/출력 예시]**
입력 : {[()]}[{}]
출력 : true

입력 : {[()]}[{}[
출력 : false 

입력 : {[()]}[{)]
출력 : false

입력 : {[(]}[{}]
출력 : false 

입력 : }])]
출력 : false

다음 출제자는 신동식 책임님 부탁드립니다.

**Comment by hrkim28** [comment]
출석합니다

**Comment by choiswon** [comment]
출첵합니다.

**Comment by tjdah13** [comment]
출석합니다

**Comment by cnsjunwoolee** [comment]
생각보다 어렵네요.. 졸려서 그런가?

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by yelgit** [comment]
우선 출첵합니다. 생각은 무지 단순한거 같은데... 코딩은 어떨런지...

**Comment by khbanhub** [comment]
출첵합니다

**Comment by jinkwui** [comment]
출석합니다.

**Comment by ywlimx** [comment]
출석합니다

**Comment by ximpley** [comment]
가장 메모리를 적게 쓰는 Coding을 보고 싶어요.

**Comment by hjkimsky** [comment]
출석합니다.

**Comment by junwc** [comment]
출석합니다. 파이썬 리뷰어는 임영찬 책임입니다.
