### ISSUE TITLE
29일차 문제(20190312) - 조합 Combination

### ISSUE THREAD

**Issue by hrkim28** [hrkim28/TCT#35]
#### 신동식 책임님 요청으로 등록합니다.
**마지막 출제자는 반경호 책임님(@khbanhub) 입니다.**
<hr/>  

### [문제]
**출력과 같은 결과를 얻기 위해서 아래 메서드 makeCombination를 구현하시오. 
** 단, 출력 순서는 아래와 달라도 상관 없습니다. 모든 결과는 도출되어야 합니다.**
```
public static void main(String[] args) {
    int[][] result = makeCombination(4, 4);
    for (int i = 0; i < result.length; i++) {
        for (int j = 0; j < result[i].length; j++) {
            System.out.print(result[i][j]);
        }
        System.out.println("");
    }
}

private static int[][] makeCombination(int N, int K) {
    // 구현하시오.
    return null;
}
```

#### (.......... 는 결과값이 많아서 줄임 표시한 것이고 실제로 모든 값이 출력되어야 합니다.)

0000
0001
0002
0003
0010
0011
0012
0013
0020
0021
..........
0333
1000
1001
1002
1003
1010
1011
1012
..........
3331
3332
3333

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by cherrylime** [comment]
우출2

**Comment by yelgit** [comment]
출첵합니다. 한바퀴 끝이 보이네요. 모두들 고생이 많으셨습니다.^^

**Comment by choiswon** [comment]
출석합니다

**Comment by jinkwui** [comment]
출석합니다.

**Comment by junwc** [comment]
출석합니다. 파이썬 리뷰어는 홍세은 선임입니다.

**Comment by ohardcore** [comment]
출석합니다..

**Comment by cnsjunwoolee** [comment]
좋은 문제네요. 오늘 청주로 출장 때문에 참석을 못했습니다.

**Comment by hjkimsky** [comment]
출석합니다.

**Comment by ywlimx** [comment]
출석합니다

**Comment by hrkim28** [comment]
출석합니다.
