### ISSUE TITLE
3일차 문제(20190117)

### ISSUE THREAD

**Issue by clamp83** [hrkim28/TCT#4]
**문제**
윤영이는 3의 배수 마니아이다. 그는 모든 자연수를 3개의 3의 배수의 자연수로 분해하는 것을 취미로 가지고 있다. 문득 그는 자신에게 주어진 수를 3개의 3의 배수로 분리하는 경우의 수가 몇 개인지 궁금해졌다. 
하지만 윤영이는 마지막 학기이기 때문에 이런 계산을 하기에는 너무 게을러졌다. 
그래서 당신에게 이 계산을 부탁했다.

즉, 임의의 3의 배수 자연수 n이 주어졌을 때, 해당 수를 3의 배수의 자연수 3개로 분리하는 방법의 개수를 출력해라. 
단 분해한 수의 순서가 다르면 다른 방법으로 간주한다.
예를 들어 12 = 3 + 6 + 3 과 12 = 3 + 3 + 6 은 다른 방법이다.

**입력**
임의의 3의 배수 자연수 n이 주어진다. (3 ≤ n ≤ 3000)

**출력**
자연수 n을 분해하는 방법의 개수를 출력하라

**예제1**
입력: 9
출력: 1

9 = 3+3+3 외 다른 방법이 없기에 1

**예제2**
입력: 12
출력: 3

12 = 3 + 3 + 6, 
12 = 3 + 6 + 3, 
12 = 6 + 3 + 3 
총 3개

**Comment by hrkim28** [comment]
차주 월요일 문제 출제자 지정 부탁 드립니다.

**Comment by ximpley** [comment]
월요일 출제자는 이현서 책임님입니다.
