### ISSUE TITLE
TCT 학습활동 20190124

### ISSUE THREAD

**Issue by cnshong** [hrkim28/TCT#8]
[문제]
1보다 큰 자연수 중에서 1과 자기 자신을 제외한 약수가 없는 자연수를 소수라고 한다.
예를 들어, 5는 1과 5를 제외한 약수가 없기 때문에 소수이다.

2보다 큰 모든 짝수는 두 소수의 합으로 나타낼 수 있다.
예를 들면, 4=2+2,6=3+3, 8=3+5 이다.

2보다 큰 짝수 n에 두 소수로 출력하는 프로그램을 작성하여라.
만약 그 가지수가 여러가지라면 두 소수의 차이가 가장 적은 것을 출력하여라

예를 들면,
6을 두 소수로 나누는 경우의 수는 두가지 이다.
3,3과 5,1 이 두가지 경우 중 두 소수의 차이가 적은 3 3을 출력하면 된다.

[입력]
n (4<=n<=10,000)

[출력]
두 수를 공백으로 구분하여 출력

[예제]
입력 
16
출력 
5 11

**Comment by ximpley** [comment]
연속해서 수를 다루는 문제네요. 수학 공부부터 다시 해야 하나 하고 고민하시는 분들 생길듯 하네요. ^^; 다들 비슷하니까 고민마시고 한 번 해보세요. :white_check_mark:

**Comment by Kimsiwon75** [comment]
우선 출석체크부터

**Comment by hjkimsky** [comment]
문제 확인부터~~

**Comment by cnshong** [comment]
다음 출제자는 나혜정 선임입니다.

**Comment by BBOMS** [comment]
출첵입니다 :+1:

**Comment by youngmi-won** [comment]
:+1:

**Comment by youngmi-won** [comment]
:heart: :heartbeat:

**Comment by clamp83** [comment]
출첵입니다.
