### ISSUE TITLE
8일차문제(20190128)

### ISSUE THREAD

**Issue by hjna1987** [hrkim28/TCT#9]
1. 문제
영어로 된 문장이 주어졌을 때, 대소문자 구분없이 가장 많이 사용된 알파벳을 출력하는 프로그램을 작성하시오.
 	
2. 입력
첫째 줄부터 글의 문장이 주어진다. 
글은 최대 5000글자로 구성되어 있고, 공백, 알파벳, 특수문자, 엔터로만 이루어져 있다. 
그리고 적어도 하나의 알파벳이 있다.
		  
   [case1]
   I think I'm lost.
   [case2]
   I think I'm lost.I can't tell.
   [case3]
   I think I'm lost. I can't tell what's where.

 3. 출력 
가장 많이 사용된 알파벳과 그 횟수를 출력한다. 
가장 많이 쓰인 알파벳이 여러개인 경우 알파벳순서대로 모두 출력한다.
	  
    [case1]
    가장많이 쓰인 알파벳 : i = 3회		  
    [case2]
    가장많이 쓰인 알파벳 : i, t = 4 회
    [case3]
    가장많이 쓰인 알파벳 : t = 5 회

**Comment by hjna1987** [comment]
다음 출제자는 이동근책임님 입니다  :D

**Comment by Kimsiwon75** [comment]
우선 출석체크부터

**Comment by yelgit** [comment]
출첵

**Comment by choiswon** [comment]
출첵입니다.

**Comment by ximpley** [comment]
많이 나온 문제네요. 또 나올만 하겠죠.

**Comment by BBOMS** [comment]
늦은 출첵입니다
